project:
  type: book

book:
  #title: "Buddhi GV"
  #subtitle: "Democratizing Brain Computer Interfaces to foster curiosity. experimentation and speculation"
  #cover-image: images/cover.jpg
  #repo-url: https://github.com/abhiramjois/buddhigv
  favicon: images/bgv.png
  chapters: 
    - index.qmd
    - part: "Curiosity"
      chapters:
        - bci.qmd
        - non_invasive_eeg.qmd
        - med.qmd
        - consumer.qmd
        - art.qmd
    - part: "Experimentation"
      chapters:  
        - record.qmd
        - byb.qmd
        - brbay.qmd
    - part: "Speculation"
      chapters:
        - summary.qmd
    - references.qmd

bibliography: references.bib
biblio-style: authoryear

format:
  html:
    title-block-style: none
    bread-crumbs: false 
    theme: cyborg
    number-sections: false
    toc-title: "On this page"
    toc: true
    
  pdf:
    documentclass: scrreprt

editor: visual

