project:
  type: book

book:
  title: "Buddhi GV"
  subtitle: "Democratizing Brain Computer Interfaces to foster curiosity. experimentation and speculation"
  author: "Abhiram Jois"
  cover-image: /images/bgv.png
  chapters: 
    - index.qmd
    - part: "Curiosity"
      chapters:
        - bci.qmd
        - non_invasive_eeg.qmd
    - part: "Experimentation"
      chapters:  
        - intro.qmd
    - part: "Speculation"
      chapters:
        - summary.qmd
    - references.qmd

bibliography: references.bib
biblio-style: authoryear

format:
  html:
    title-block-style: none
    bread-crumbs: false 
    theme: journal
    number-sections: false
    
  pdf:
    documentclass: scrreprt

editor: visual

