# EEG in Art and Performance

### MindPool

MindPool was an installation that encouraged self-reflection through biofeedback. It collected alpha, beta, delta, and theta brainwaves to create ripples in 48 shallow pools of water thanks. The installation is the work of an artist called Lisa Park. [@long2013]

{{< video https://www.youtube.com/watch?v=F-r-ZGE4z_M >}}

### Original Ideal

With Original Ideal, Chasserot explores new ideas about beauty being a function of personal identity, as opposed to the contexts of societal standards. The first step involves capturing images of his subjects in minimal, basic, and effortless states. Followed by digital modifica- tions to the captured image. The participants are then hooked up to an Emotiv EEG brain scanner, and shown 50 edited images. Those brain scans are then analyzed for brain activity that can denote a positive emotional reaction to understand how our brain responds to societal standards of beauty. [@mufson2014]

{{< video https://vimeo.com/83598327 >}}

### Interactive Brain Light

Interactive Brain Light is artist Laura Jade’s new EEG- controlled installation, Brain Light Project is a light sculpture designed to create a biofeedback loop of light, sound, and thought. In a process developed by Jade, neuroscientist Peter Simpson-Young, and programmer Sam Gentle, the installation becomes a real-time visualization of visitors’ alpha, theta, and beta brainwaves. [@laurajade2015]

{{< video https://www.youtube.com/watch?v=-gA0U1WMUNg >}}
